CREATE DATABASE IF NOT EXISTS PencaUCU;
USE PencaUCU;

CREATE TABLE IF NOT EXISTS Alumnos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255),
  valor INT
);

INSERT INTO Alumnos (nombre, valor) VALUES ('Jose Varela', 48477706);

